name: Verificar Atualização da Branch

on:
  pull_request:
    types:
      - labeled
  schedule:
    - cron: '0 * * * *' # Executar a cada hora

jobs:
  verificar-atualizacao:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'autoupdate') }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout da Branch
      uses: actions/checkout@v3

    - name: Verificar se há atualizações
      run: |
        echo "Pull request ééé: ${{ toJSON(github.event.pull_request.number) }}"

        curl --location --request POST 'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels' \
          --header 'Accept: application/vnd.github.v3+json' \
          --header 'Authorization: Bearer ${{ secrets.GH_API_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "labels": ["enhancement"]
          }'
