name: Verificar Atualização da Branch

on:
  pull_request:
    types:
      - labeled
  schedule:
    - cron: '0 * * * *' # Executar a cada hora

jobs:
  verificar-atualizacao:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'autoupdate') }}

    steps:
    - name: Checkout da Branch
      uses: actions/checkout@v3

    - name: Verificar se há atualizações
      run: |
        echo "Está com o label 'autoupdate'."
