name: Verificar Atualização da Branch

on:
  pull_request:
    types:
      - labeled

jobs:
  verificar-atualizacao:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout da Branch
      uses: actions/checkout@v2

    - name: Verificar se há atualizações
      if: ${{ contains(github.event.pull_request.labels.*.name, 'autoupdate') }}
      run: |
        git fetch origin
        UPSTREAM=$(git rev-parse '@{upstream}')
        LOCAL=$(git rev-parse '@')

        if [ $UPSTREAM != $LOCAL ]; then
          echo "A branch precisa ser atualizada."
          # Coloque aqui os comandos ou scripts para realizar a atualização
        else
          echo "A branch está atualizada."
        fi
