name: Verificar Atualização da Branch

on:
  pull_request:
    types:
      - labeled
  schedule:
    - cron: '0 * * * *' # Executar a cada hora

jobs:
  update-branch:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'autoupdate') }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout da Branch
      uses: actions/checkout@v3

    - name: Update branch
      run: |
        echo "Pull request head ééé: ${{ toJSON(github.event.pull_request.head) }}"

        git fetch origin
        git checkout ${{ github.event.pull_request.head.ref }}
        git merge origin/${{ github.event.pull_request.head.ref }}
        git push origin ${{ github.event.pull_request.head.ref }}

  remove-label:
    needs: [update-branch]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Remove autoupdate label
        run: |
          # Remove o label de autoupdate.
          # https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28
          curl -L -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_API_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/autoupdate

        - name: Output information
          run: |
            echo "Something went wrong"
            echo "${{ toJSON(github) }}"
