name: Verificar Atualização da Branch

on:
  pull_request:
    types:
      - labeled
  schedule:
    - cron: '0 * * * *' # Executar a cada hora

jobs:
  verificar-atualizacao:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'autoupdate') }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout da Branch
      uses: actions/checkout@v3

    - name: Verificar se há atualizações
      run: |
        echo "A branch atual é: $(git rev-parse --abbrev-ref HEAD)"
        git fetch origin

        # Mesclar a branch remota (main) com a branch local usando a estratégia 'ours'
        git merge -s ours origin/main -m "Merge branch 'main' into $(git rev-parse --abbrev-ref HEAD)"

        # Forçar a atualização da branch remota com as alterações mescladas
        git push origin HEAD
